export const CONTRACT_ADDRESS = "CC4J3QDHYNVWSRYHEI3R6I74QJWVVYLP3HBZTRRMDX7JUV4IDLPXSEPQ";
export const FACTORY_CONTRACT_ADDRESS = "CCGVCTV6US4JYE443Y66RPBKLUPHPKC7LZ6SWBC7U7P3JSNXF4Q65YBF";
export const Network = "https://rpc-futurenet.stellar.org";
export const SUPPORTED_NETWORK = "FUTURENET";
export const SUPPORTED_NETWORK1 = "STANDALONE";

